### PR TITLE
Warn on incorrect start & sub start codes.

### LINKED ISSUE #46: Packet Disector doesn't catch illegal sub start codes
E.g. 
0xcc, 0x02, 0x18, 0x7a, 0x70, 0x00, 0x00, 0x00, 0x00, 0x7a, 0x70, 0x12,
0x34, 0x56, 0x78, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x00, 0x02, 0x00,
0x03, 0xe0

### PR DESCRIPTION
**Pull request by nomis52**
This also creates a filter so we can start moving the presentation logic out of
the controller.

Closes #46

### CODE REVIEW

File: static/js/rdm.js [hunk 1]
```diff
@@ -1,2 +1,985 @@
...
-//# sourceMappingURL=rdm.js.map
\ No newline at end of file
+angular.module('rdmApp', [])
```
Comment (peternewman) [inline static/js/rdm.js]: This isn't minified anymore.

**Comment by peternewman** [comment]
LGTM, just one comment.

**Comment by nomis52** [comment]
My next commit is going to remove that file :)
